name: embrace
description: A comprehensive observability and monitoring platform for iOS and Android apps built with Flutter.
version: 4.3.0
homepage: https://embrace.io
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
flutter:
  plugin:
    platforms:
      android:
        default_package: embrace_android
      ios:
        default_package: embrace_ios
dependencies:
  embrace_android: ">=4.3.0 <4.4.0"
  embrace_ios: ">=4.3.0 <4.4.0"
  embrace_platform_interface: ">=4.3.0 <4.4.0"
  flutter:
    sdk: flutter
  http: ">=0.13.3 <2.0.0"
dev_dependencies:
  dartdoc: ^8.3.3
  flutter_test:
    sdk: flutter
  mocktail: ">=0.3.0 <2.0.0"
  plugin_platform_interface: ^2.0.0
  very_good_analysis: ">=3.0.2 <11.0.0"
