name: embrace_dio
description: Allows automatic Dio network capture when using the the embrace plugin.
version: 4.3.0
homepage: https://embrace.io
environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"
dependencies:
  build_runner: ^2.0.0
  build_version: ^2.0.0
  dio: '>=4.0.0 <6.0.0'
  embrace: 4.3.0
  flutter:
    sdk: flutter
  platform: ^3.1.0
  plugin_platform_interface: ^2.1.0
  embrace_platform_interface: "4.3.0"
dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ">=5.1.0 <11.0.0"
